# This is Heading

## HEADING2

In [2]:
import numpy as np

In [3]:
import numpy as np

In [4]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [5]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [6]:
d1=np.array([45,74,85,36,65,57])
d1

array([45, 74, 85, 36, 65, 57])

In [7]:
d1.shape

(6,)

In [8]:
d1.size

6

In [9]:
d1.ndim

1

In [10]:
d1[1]

74

In [11]:
d1[2]

85

In [12]:
d2=np.array([12,23,45,67,89][24,13,46,78,19])

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-12-1af2a45de5ac>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  d2=np.array([12,23,45,67,89][24,13,46,78,19])


TypeError: list indices must be integers or slices, not tuple

In [13]:
d2=np.array([12,23,45,67,89],[24,13,46,78,19])

TypeError: Field elements must be 2- or 3-tuples, got '24'

In [14]:
d1[0:3]

array([45, 74, 85])

In [15]:
d1

array([45, 74, 85, 36, 65, 57])

In [16]:
d1[0;-3]

SyntaxError: invalid syntax (<ipython-input-16-c56d970cbd2a>, line 1)

In [17]:
d1[-1]

57

In [18]:
d1[:-3]

array([45, 74, 85])

In [19]:
data=np.array(['range',123,"cse","A",45.25])

In [20]:
data

array(['range', '123', 'cse', 'A', '45.25'], dtype='<U5')

In [24]:
import time
start_time=time.time()
list1=[x for x in range(1,100000)]
list2=[y for y in range(1,100000)]
op=list(map(lambda x,y:x*y,list1,list2))
end_time=time.time()
print("time taken by the list",end_time-start_time)

time taken by the list 0.0312349796295166


In [25]:
import time
start_time1=time.time()
ar1=np.array(list1)
ar2=np.array(list2)
ar1*ar2
end_time1=time.time()
print("time taken by numpy is",end_time1-start_time1)

time taken by numpy is 0.015624284744262695


In [26]:
d2=np.array([[45,74,36],[96,87,69],[14,25,63]])
d2

array([[45, 74, 36],
       [96, 87, 69],
       [14, 25, 63]])

In [27]:
d2.ndim

2

In [28]:
d2.shape

(3, 3)

In [29]:
d2.size

9

In [30]:
d2[0]

array([45, 74, 36])

In [31]:
d2[1]

array([96, 87, 69])

In [32]:
d2[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [33]:
d2[2]

array([14, 25, 63])

In [34]:
d2[0,2]

36

In [35]:
max[d2[1]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [36]:
d2[1].max()

96

In [37]:
np.max(d2[1])

96

In [38]:
d2[:,2]

array([36, 69, 63])

In [39]:
max(d2[:,2])

69

In [40]:
min(d2[:,0])

14

In [41]:
max(d2[0:])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [42]:
max(d2[2])

63

In [43]:
sum(d2[0,1,2])

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [44]:
sum(d2(axis=0))

TypeError: 'numpy.ndarray' object is not callable

In [45]:
d2.sum(axis=0)

array([155, 186, 168])

In [46]:
d2.sum()

509

In [47]:
d2.sum(axis=1)

array([155, 252, 102])

# axis=1 for columns(adding)

# axis=0 for adding rows

In [48]:
d3=np.array([[[1,2,3],[4,5,6]],
             [[7,8,9],[10,11,12]]])
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### 255x125x3
 ### here 3 indicates RGB(RED,GREEN,BLUE)

In [49]:
d3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
d3[0,0]

array([1, 2, 3])

In [51]:
d3[0,0,1]

2

### Arrange()

In [52]:
print[x for x in range(1,10)]

SyntaxError: invalid syntax (<ipython-input-52-668b85af348f>, line 1)

In [53]:
range(1,10)

range(1, 10)

In [55]:
for i in range(1,11):
    print(i,end="  ")

1  2  3  4  5  6  7  8  9  10  

In [57]:
for i in arange(0,10):
    print(i,end="  ")

NameError: name 'arange' is not defined

In [58]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
for i in range(1,6,0.5):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [60]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [61]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

# linspace

### divide the parts equally

## arange
### find use the equal and the un used is removed

# zeos matrix

In [63]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [67]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
np.tile(10,[5,5])

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [73]:
d21=np.array([[14,25,36,41,52],[24,51,35,15,16]])
d21

array([[14, 25, 36, 41, 52],
       [24, 51, 35, 15, 16]])

In [74]:
add_marks=np.tile(5,[2,5])

In [76]:
add_marks

NameError: name 'add_marks' is not defined

In [77]:
add_marks=np.tile(5,[2,5])
add_marks

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [78]:
final_marks=d21+add_marks
final_marks

array([[19, 30, 41, 46, 57],
       [29, 56, 40, 20, 21]])

In [79]:
mat=np.array([[1,10,20],[2,20,30],[3,45,55]])
mat

array([[ 1, 10, 20],
       [ 2, 20, 30],
       [ 3, 45, 55]])

In [80]:
np.linalg.eig(mat)

(array([79.2418833 , -0.76390403, -2.47797927]),
 array([[-0.27476378, -0.98372828, -0.86503683],
        [-0.44175308, -0.11022856, -0.37213216],
        [-0.85402523,  0.14187439,  0.33649509]]))

In [81]:
np.linalg.inv(mat)

array([[-1.66666667,  2.33333333, -0.66666667],
       [-0.13333333, -0.03333333,  0.06666667],
       [ 0.2       , -0.1       ,  0.        ]])

# random

In [82]:
np.random.random(10)

array([0.16288285, 0.93341846, 0.18879128, 0.83430851, 0.45582969,
       0.82945095, 0.56825236, 0.05408974, 0.86543559, 0.09667887])

In [83]:
np.random.random(1,10)

TypeError: random() takes at most 1 positional argument (2 given)

In [84]:
np.random.randint(10)

6

In [85]:
np.random.random(10)

array([0.02263908, 0.39606484, 0.62697005, 0.78615676, 0.86458192,
       0.51209367, 0.85664691, 0.66036977, 0.71005161, 0.71334708])

In [87]:
np.random.randint(10,15)

13

In [88]:
np.random.randint(10,20,30)

array([19, 18, 12, 18, 16, 11, 12, 17, 18, 12, 10, 14, 10, 18, 11, 11, 16,
       10, 18, 10, 10, 16, 10, 16, 13, 10, 17, 15, 14, 11])

In [90]:
np.random.randint(10,25,[4,6])

array([[23, 15, 17, 14, 14, 22],
       [16, 15, 14, 11, 18, 22],
       [18, 24, 18, 14, 24, 14],
       [15, 22, 19, 11, 15, 16]])

In [91]:
np.random.rand(10)

array([0.73598802, 0.93499955, 0.76554251, 0.24873441, 0.90206101,
       0.27869544, 0.20804855, 0.93124827, 0.73144746, 0.98295215])

In [92]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [94]:
np.random.randint(1,13,[4,3])

array([[ 1,  5,  5],
       [10, 12,  5],
       [11,  1,  4],
       [ 3, 12,  5]])

In [95]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [96]:
np.arange(1,49).reshape(4,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [101]:
np.arange(1,37).reshape(3,4,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [102]:
np.sin(90)

0.8939966636005579

#### default consider as the radians

#### so the values of the sin changes

In [103]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [104]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [105]:
np.tan(45)

1.6197751905438615

In [106]:
np.sinh(10)

11013.232874703393

In [107]:
np.arcsin(90)

<ipython-input-107-83f060775ee7>:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(90)


nan

In [108]:
array=np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
max(array())

TypeError: 'numpy.ndarray' object is not callable

In [110]:
ayyay.max()

NameError: name 'ayyay' is not defined

In [111]:
array.max()

9

In [112]:
# for finding max value index
array.argmax()

8

In [113]:
array.min()

1

In [114]:
# for finding the min value index
array.argmin()

0

In [115]:
sec1=np.array(np.random.randint(10,20,[4,4,]))
sec1

array([[18, 14, 10, 16],
       [19, 11, 16, 10],
       [16, 16, 18, 12],
       [19, 14, 19, 13]])

In [117]:
sec2=np.array(np.random.randint(1,10,[4,4]))
sec2

array([[1, 4, 2, 3],
       [2, 5, 5, 8],
       [7, 9, 3, 3],
       [5, 3, 1, 1]])

In [118]:
# the vstack add the above 2 sec those are sec1 and sec2 and print the result in vertical format
np.vstack((sec1,sec2))

array([[18, 14, 10, 16],
       [19, 11, 16, 10],
       [16, 16, 18, 12],
       [19, 14, 19, 13],
       [ 1,  4,  2,  3],
       [ 2,  5,  5,  8],
       [ 7,  9,  3,  3],
       [ 5,  3,  1,  1]])

In [119]:
# hstack adds the sec above in the horizantal format
np.hstack((sec1,sec2))

array([[18, 14, 10, 16,  1,  4,  2,  3],
       [19, 11, 16, 10,  2,  5,  5,  8],
       [16, 16, 18, 12,  7,  9,  3,  3],
       [19, 14, 19, 13,  5,  3,  1,  1]])

In [120]:
# the both hstack and the column stack are equal
np.column_stack((sec1,sec2))

array([[18, 14, 10, 16,  1,  4,  2,  3],
       [19, 11, 16, 10,  2,  5,  5,  8],
       [16, 16, 18, 12,  7,  9,  3,  3],
       [19, 14, 19, 13,  5,  3,  1,  1]])

In [121]:
sec1+sec2

array([[19, 18, 12, 19],
       [21, 16, 21, 18],
       [23, 25, 21, 15],
       [24, 17, 20, 14]])

In [122]:
sec1*sec2

array([[ 18,  56,  20,  48],
       [ 38,  55,  80,  80],
       [112, 144,  54,  36],
       [ 95,  42,  19,  13]])

In [123]:
# multiply the value inthe same rows of both the sec1 and sec2
sec1@sec2

array([[196, 280, 152, 212],
       [203, 305, 151, 203],
       [234, 342, 178, 242],
       [245, 356, 178, 239]])

In [124]:
sec1.dot(sec2)

array([[196, 280, 152, 212],
       [203, 305, 151, 203],
       [234, 342, 178, 242],
       [245, 356, 178, 239]])

In [125]:
# convert rows to columns and columns into rows
sec1.transpose()

array([[18, 19, 16, 19],
       [14, 11, 16, 14],
       [10, 16, 18, 19],
       [16, 10, 12, 13]])

In [126]:
sc1.trace()

NameError: name 'sc1' is not defined

In [127]:
# add the diagonal elements
sec1.trace()

60

#### split

In [130]:
np.hsplit(sec1,2)

[array([[18, 14],
        [19, 11],
        [16, 16],
        [19, 14]]),
 array([[10, 16],
        [16, 10],
        [18, 12],
        [19, 13]])]

In [131]:
# to split in the matrix form
np.hsplit(sec1,[2,2])

[array([[18, 14],
        [19, 11],
        [16, 16],
        [19, 14]]),
 array([], shape=(4, 0), dtype=int32),
 array([[10, 16],
        [16, 10],
        [18, 12],
        [19, 13]])]

In [132]:
np.vsplit(sec1,[2,3])

[array([[18, 14, 10, 16],
        [19, 11, 16, 10]]),
 array([[16, 16, 18, 12]]),
 array([[19, 14, 19, 13]])]

In [133]:
np.abs(100.25)

100.25

In [134]:
np.abs(-100.25)

100.25

In [135]:
np.all(sec1>0)

True

In [136]:
np.all(sec1<0)

False

In [137]:
np.round(12.36)

12.0

In [138]:
np.round(12.63)

13.0

In [139]:
np.floor(10.23)

10.0

In [140]:
np.ceil(10.96)

11.0

In [141]:
np.ceil(10.23)

11.0